name: Release messages to discord announcement channel

on:
  release:
    types:
      - created

jobs:
  run_main:
    runs-on: ubuntu-18.04
    name: Sends custom message on release
    steps:
      - name: Sending message on software channel
        uses: nhevia/discord-styled-releases@main
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
